### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by srwgin** [mikinano7/gbf_cli#1]
1.I upload it to my website
2.I create twitter app
3.I get Keys and Access Tokens
4.I create default.json in config folder and write in it
but it not work
only show 
救援依頼

5秒毎に更新されます
nothing else
what is the problem
thank you

**Comment by srwgin** [comment]
after some research
I install nodejs then what should I do
thank you

**Comment by srwgin** [comment]
D:\temp\gbf\others\gbf_cli-master>node index.js
D:\temp\gbf\others\gbf_cli-master\index.js:18
app.on('window-all-closed', function() {
   ^

TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (D:\temp\gbf\others\gbf_cli-master\index.js:18:4)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3

**Comment by srwgin** [comment]
![1](https://cloud.githubusercontent.com/assets/1639177/16356130/5e448712-3b00-11e6-8b66-3f734725d37b.jpg)
finally run it
but it not work

**Comment by srwgin** [comment]
after I use vpn it work now thank you

**Comment by mikinano7** [comment]
I'm sorry about the description of how to use is insufficient.
But I don't know what the network is concerned.

Maybe `Uncaught TypeError: Cannot read property 'statuses' of null` is caused by Twitter API request error.
Can you use 'twitter' module and request Twitter API normally?
If you can't, please try install 'twitter' module in your local project directry.
`npm install twitter` ( Not use `-g` option. )

And I will fix this dependency problem. ( Add `node_modules/twitter` module. )

**Comment by mikinano7** [comment]
Added depending librrary in project directry.
https://github.com/mikinano7/gbf_cli/commit/6326e8145f50738e37d0df6423d1c703b3f6574e
